### PR TITLE
[Hacktoberfest Contribution] Added Dalai Lama quotes (+ Bonus improvements)

### PR DESCRIPTION
**Pull request by Glis**
**Hello there!!** ☺️ 

I took your cue and added some Dalai Lama quotes in its own new file.

Also added:
- Corresponding specs
- Mini improvement in the dharma_quotes.rb file favoring further contribution there (a687688)
- [Rubocop](https://github.com/rubocop-hq/rubocop) used vastly in almost any ruby repo i know for mantainign ruby best practices. you can further tweak its config by adding/removing options in the `.rubocop.yml`, (more details at 7c28e5e)

Let me know if there's something to change!

I'll stay tuned

### CODE REVIEW

**Comment by Glis** [comment]
Hello @Evie-Skinner18 😊 

Could you check this? I'm here if something needs to be changed!

**Comment by Glis** [comment]
Hi @Evie-Skinner18 😄 !
I think this PR is not be eligible to qualify for the Hacktoberfest anymore, but nvm. I hope it still could be of use for your project. I had real fun doing it and i think it's a nice gem.

Let me know if you need me to change something. I'm staying tuned 😋

**Comment by Evie-Skinner18** [comment]
Hi @Glis ! I'm so sorry for the late reply :scream:  I've been a bit unwell lately. Thank you ever so much for your PR :heart: and I'm really looking forward to seeing RuboCop in action. Thank you for helping me learn about this and improving the gem, I really appreciate it!

**Review by Evie-Skinner18 — APPROVED** [review]
@Glis your code is beautiful! Thank you for introducing me to array.flatten and for the Dalai Lama quotes :monkey:  Stay safe and I hope to collaborate with you again this year!

**Comment by Glis** [comment]
Thank you for your review @Evie-Skinner18 ! Hope you get better. these are rough times to get by, but we shall prevail! Really wish you health and wellbeing 😊 

The pleasure was all mine. I hope these changes had been useful.
See you next year! 😉

**Pull request merged**
